# Generated by Django 2.0.5 on 2018-05-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='sender_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
