# Generated by Django 2.0.5 on 2018-05-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_log_sender_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='broadcast',
            field=models.BooleanField(default=False),
        ),
    ]
