# Generated by Django 2.0.5 on 2018-05-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_message_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='broadcasted',
            field=models.NullBooleanField(default=True),
        ),
    ]
